import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const pageStyle = {
    maxWidth: '48rem',
    marginRight: 'auto',
    marginLeft: 'auto',
    padding: '1rem',
  };
  const childrenStyle = {
    margin: '2rem',
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={pageStyle}>
          <Navbar />
          <div style={childrenStyle}>{children}</div>
        </div>
      </body>
    </html>
  )
}
